In [6]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [7]:
data = pd.DataFrame(dict(area =[2600,3600,4600,5600,6600,7600],
                        price =[250000,350000,450000,550000,650000,750000],
                        bed_room=[6,8,5,7,2,4],
                        age=[20,21,22,23,25,24,]))

In [8]:
data

area   price  bed_room  age
0  2600  250000         6   20
1  3600  350000         8   21
2  4600  450000         5   22
3  5600  550000         7   23
4  6600  650000         2   25
5  7600  750000         4   24

In [9]:
# data.to_csv("multiple.csv",index=False)

In [10]:
df = pd.read_csv("multiple.csv")
df

area   price  bed_room  age
0  2600  250000       6.0   20
1  3600  350000       8.0   21
2  4600  450000       NaN   22
3  5600  550000       5.0   23
4  6600  650000       2.0   25
5  7600  750000       4.0   24

In [11]:
import math as mt 
med = mt.floor(df.bed_room.median())
med

5

In [12]:
df.bed_room =df.bed_room.fillna(med)
df

area   price  bed_room  age
0  2600  250000       6.0   20
1  3600  350000       8.0   21
2  4600  450000       5.0   22
3  5600  550000       5.0   23
4  6600  650000       2.0   25
5  7600  750000       4.0   24

In [13]:
reg = linear_model.LinearRegression()

In [14]:
reg.fit(df[["area","bed_room","age"]],df.price)

LinearRegression()

In [15]:
reg.predict([[6000,5,34]])

C:\Users\suvas\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590000.])

In [16]:
reg.coef_ , reg.intercept_


(array([ 1.00000000e+02, -2.67911307e-17,  1.21742871e-17]),
 np.float64(-10000.000000000058))

In [17]:
import pickle

In [18]:
with open('model_pickle','wb') as f:  #wb if write binary 
    pickle.dump(reg,f)
    

In [19]:
with open('model_pickle','rb') as f : # rb is  read binary
    model = pickle.load(f)
    

In [20]:
model.predict([[6000,6,6]])

C:\Users\suvas\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590000.])

In [21]:
###this is joblib 



In [22]:
import joblib

In [23]:
joblib.dump(reg,"model_joblib")

['model_joblib']

In [24]:
mj = joblib.load("model_joblib")

In [26]:
mj.predict([[6000,6,6]])

C:\Users\suvas\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590000.])